# gradle/libs.versions.toml

[versions]
# Build Tools & Core
gradlePlugin = "8.3.2"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"
compileSdk = "35"
minSdk = "26"
targetSdk = "35"
versionCode = "22"
versionName = "0.5.7"
firebaseBom = "32.7.0"
googleServicesPlugin = "4.4.2"
firebasePerfPlugin = "1.4.2"
firebaseCrashlyticsPlugin = "3.0.6"

# AndroidX Core & UI (SDK 34 호환 버전)
androidxCore = "1.13.1"
androidxSplashscreen = "1.0.1"
androidxSecurityCrypto = "1.1.0-alpha06"
androidxAppCompat = "1.6.1"
androidxActivity = "1.9.0"
androidxFragment = "1.7.1"
androidxConstraintLayout = "2.1.4"
androidxRecyclerview = "1.3.2"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.7"
androidxRoom = "2.6.1"
androidxDatastore = "1.0.0"
androidxArchCoreTesting = "2.2.0" # 테스트용
androidxMedia = "1.7.0"
lottie = "6.6.6"
circleImageView = "3.1.0"
shimmer = "0.5.0" # 스켈레톤

# Google (SDK 34 호환 버전)
material = "1.11.0"
hilt = "2.49"

# Kotlinx
coroutines = "1.9.0"

# Networking
retrofit = "2.11.0"
okhttp = "4.12.0"
moshi = "1.15.1"

# Logging (Example: Timber)
timber = "5.0.1"

# Testing
junit = "4.13.2"
androidxTestExtJunit = "1.2.1"
androidxTestEspresso = "3.6.1"
mockk = "1.13.10"
turbine = "1.1.0" # Flow 테스트용
truth = "1.1.5"
jacoco = "0.8.11" # 테스트 커버리지 측정 플러그인
ktlintPlugin = "12.1.1"
ktlintCli = "1.2.1"

# DI - JSR 330
javaxInject = "1"
activity = "1.9.0"
firebaseConfigKtx = "22.1.1"

# Cognito
appauth = "0.11.1"

# Glide
glide = "4.16.0"

# CircleIndicator
circleindicator = "2.1.6"

# Kizitonwose Calendar
kizitonwoseCalendar = "2.6.0"

# Kakao SDK
kakaoMap = "2.12.17"

# Google Location Services
playServicesLocation = "21.3.0"

# TED Clustring
tedClustering = "1.0.2"

[libraries]

# Gradle 플러그인 아티팩트 정의
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
# KSP 아티팩트
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp"}
# Hilt 플러그인 아티팩트
hilt-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt"}
firebase-performance-plugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

# AndroidX Core & UI
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashscreen" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "androidxSecurityCrypto" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "androidxMedia" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }

# AndroidX Lifecycle (ViewModel, LiveData, Runtime)
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidxLifecycle" }

# AndroidX Navigation
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" } # 테스트용

# AndroidX Room (Local DB Example)
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" } # KSP/Kapt

# AndroidX DataStore (Preferences Example)
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }

# Hilt (DI)
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" } # KSP/Kapt
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" } # 테스트용

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" } # 테스트용

# Networking (Example: Retrofit, OkHttp, Moshi)
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" } # KSP/Kapt

# Logging (Example: Timber)
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
ktlint-gradle-plugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintPlugin" }
ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlintCli" }

# DI - JSR 330
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

# Firebase BoM
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
# Firebase SDKs
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-config-ktx = { group = "com.google.firebase", name = "firebase-config-ktx", version.ref = "firebaseConfigKtx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }

# Cognito
appauth = { group = "net.openid", name = "appauth", version.ref = "appauth" }

# Glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }


# CircleIndicator
circleindicator = { group = "me.relex", name = "circleindicator", version.ref = "circleindicator" }

# CircleImageView
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleImageView" }

# Kizitonwose Calendar
kizitonwose-calendar-view = { group = "com.kizitonwose.calendar", name = "view", version.ref = "kizitonwoseCalendar" }

# Kakao SDK
kakao-map = { group = "com.kakao.maps.open", name = "android", version.ref = "kakaoMap" }

# Google Location Services
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

# TED Clustring
ted-clustering = { group = "io.github.ParkSangGwon", name = "tedclustering", version.ref = "tedClustering" }

[plugins]
# Android Gradle Plugins
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }

# Kotlin Plugins
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# KSP Plugin
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Hilt Plugin
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# Navigation Safe Args Plugin
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }

# Firebase 플러그인
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }

# Jacoco Plugin
jacoco = { id = "org.gradle.jacoco", version.ref = "jacoco" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
